export const EMAIL_CHANGED = 'email_changed'
export const PASSWORD_CHANGED = 'password_changed'
export const LOG_USER_IN_SUCCESS = 'log_user_in_success'
export const LOG_IN_ERROR = 'log_in_error'
export const IS_LOG_IN_LOADING = " is_log_in_loading"
export const USER_CHANGED = 'user_changed'
export const USER_NO_CHANGED = 'user_not_changed'
export const USER_LOG_OUT = 'user_log_out'
export const USER_SET_MOBILE = 'user_set_mobile'
export const USER_UPDATE_MOBILE = 'user_update_mobile'
export const USER_LISTEN_MOBILE = 'user_listen_mobile'
export const GET_CURRENTUSER = 'get_CurrentUser'
export const LISTEN_ITEMS = "listen_for_items"